-- 강원도에 위치한 생산공장 목록 출력하기
SELECT FF.FACTORY_ID
    , FF.FACTORY_NAME
    , FF.ADDRESS
FROM FOOD_FACTORY FF
-- WHERE FF.ADDRESS LIKE '강원도%'
WHERE SUBSTR(FF.ADDRESS, 1, 3) = '강원도'
ORDER BY FF.FACTORY_ID

-- 흉부외과 또는 일반외과 의사 목록 출력하기
SELECT DR.DR_NAME
    , DR.DR_ID
    , DR.MCDP_CD
    , TO_CHAR(DR.HIRE_YMD, 'YYYY-MM-DD')
FROM DOCTOR DR
WHERE DR.MCDP_CD = 'CS' OR DR.MCDP_CD = 'GS'
-- WHERE DR.MCDP_CD IN ('CS', 'GS')
ORDER BY DR.HIRE_YMD DESC, DR.DR_NAME

-- 12세 이하인 여자 환자 목록 출력하기
SELECT PT.PT_NAME
    , PT.PT_NO
    , PT.GEND_CD
    , PT.AGE
    , CASE
        WHEN PT.TLNO IS NULL THEN 'NONE'
        ELSE PT.TLNO
      END
      -- , DECODE(PT.TLNO, NULL, 'NONE', PT.TLNO)
      -- , NVL(PT.TLNO, 'NONE')
RKXFROM PATIENT PT
WHERE PT.AGE <= 12 AND PT.GEND_CD = 'W'
ORDER BY PT.AGE DESC, PT.PT_NAME

-- 인기있는 아이스크림
SELECT FH.FLAVOR
FROM FIRST_HALF FH
ORDER BY FH.TOTAL_ORDER DESC, SHIPMENT_ID

-- 상위 n개 레코드
SELECT *
FROM (
    SELECT AI.NAME
    FROM ANIMAL_INS AI
    ORDER BY DATETIME
)
WHERE ROWNUM = 1